### ISSUE TITLE
30=Я как пользователь хочу иметь возможность искать ивенты по тегу.

### ISSUE THREAD

**Issue by Anaisnet** [openworld-community/ows-events#814]
### Описание задачи
Внедрить для любых пользователей поиск с помощью фильтрации ивентов по тегу.

### Критерии приемки
В поиске выбирать теги для фильтрации ивентов могут как не зарегистрированные пользователи сайта, так и зарегистрированные:
- [ ] В фильтре поиска можно выбрать определённые теги ивентов не зарегистрированным пользователям.
- [ ] При нажатии кнопки Поиск выдаётся список ивентов с теми тегами, которые выбирали в фильтре Поиска.
- [ ] Поиск работает с разным набором тегов в ивентах: когда у найденного ивента есть другие теги, не выбранные в фильтр.
- [ ] Поиск работает с полным набором тегов в ивенте, когда набор тегов, в найденном ивенте, соответствует полностью заданным критериям (по тегам) в фильтре.

- [ ] В фильтре поиска можно выбрать определённые теги ивентов зарегистрированным пользователям и использовать поиск по 2-м схемам, указанным выше.

Поиск по 3-м видам (дописать и вынести в отдельную задачу):
- 1 тэг
- все теги
- хотя бы один из набранных

### Предполагаемая сложность
Оцените преполагаемую сложность числом из ряда Фибоначчи: 2
- Сложность
- Объём
- Риски
